### ISSUE TITLE
poll app not visible from homepage

### ISSUE THREAD

**Issue by stuartdi** [stuartdi/project1_pyany#1]
When I visit pyhxr.pythonanywhere.com, I receive the template but not the app.
(this issue is my coding goal on this project tomorrow and not meant to be a public question).

Unless I find out whether this is bad form, I might use issues, for now, to set project goals.

" If you always put limit on everything you do, physical or anything else. It will spread into your work and into your life. There are no limits. There are only plateaus, and you must not stay there, you must KEEP HACKING."
Bruce Lee, 
slightly paraphrased.

**Comment by Javantea** [comment]
You can do it, the answer is a few hours of hacking away. Let me know if you need any help.

**Comment by stuartdi** [comment]
Thanks for having my back =] The encouragement helped more than I can express.

**Comment by stuartdi** [comment]
I have gone through: 
https://docs.djangoproject.com/en/1.3/intro/tutorial03/ multiple times but keep receiving TemplateSyntaxError and other errors see:
 gist -- https://gist.github.com/stuartdi/c905e15d79eb40760b5f 

Things tried so far:
 Repeated tutorial and looked for typos, went back and copy&paste to further rule out typos
(and I'll bet it ends up being a typo :)
Looked on stack e and stack o etc. most people are not using 1.3 and syntax is different. 
Looked on the pythonanywhere forums, haven't yet posted until I can thoroughly investigated
reloading the server, refreshing the page, dumping the cookie etc

typing http://pyhxr.pythonanywhere.com/                       "404"
typing http://pyhxr.pythonanywhere.com/admin/             "view does not exist "
typing http://pyhxr.pythonanywhere.com/char_sheet/     "view does not exist "

Since this is related to the first issue I did not open another issue ticket.
I'm out of time as of the writing of this and will be back again in a few hours.
Note that this is django 1.3, which I am aware is vulnerable and will be migrated / refactored later to current stable.

I think I covered everything, I did push the bad changes to master so they'll be visible in the repo.

**Comment by Javantea** [comment]
This is a pretty simple bug. The 404 is expected because you haven't created an root url '^$'. The view does not exist for /char_sheet/ is caused by a python path issue. Look at "Python Path:" in the error message. ['/var/www', '.', '', ...] In order to import char_sheet.views, you need char_sheet to be in one of these directories, then it should work. I can see that mysite is not in that path, so you need to change the path. Using Apache and mod_wsgi, I set the following configuration option:
WSGIPythonPath /home/www/altsci:/home/www/ai3:/home/www
For pythonanywhere, there should be a simple way to set a similar configuration option. Or if you want, you could instead use mysite.char_sheet.views.index.
I'm glad that you're planning on upgrading Django. It has a serious problem with backwards compatibility which means that each time you choose not to upgrade, you fall further behind. At times I say bad things about Django, but it's what I use.
Good luck.

**Comment by stuartdi** [comment]
It seemed that I solved the 404. But I was testing on 127.0.0.0:8080 and it worked but when hitting it from the web it doesn't. Also when I add mysite to the wsgi path it throws an "unhandled exception"
for instance:
<pre>
#add your project directory to the sys.path 
project_home = u'/home/pyhxr/Proj/project1_pyany/'
if project_home not in sys.path:
    sys.path.append(project_home)
</pre>
So, on the line project_home... if I append /project1_pyany/ with mysite it then throws the exception
<pre>
project_home = u'/home/pyhxr/Proj/project1_pyany/mysite'
</pre>
Anyway, thanks for taking a look at it I at least have an idea where to keep reading/looking.

**Comment by stuartdi** [comment]
starting over
